{{- if .Values.coder.externalsecret.enable }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.coder.externalsecret.targetName }}
  namespace: {{ .Values.coder.namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.coder.externalsecret.secretStoreRef }}
    kind: SecretStore
  refreshInterval: {{ .Values.coder.externalsecret.refreshInterval }}
  target:
    name: {{ .Values.coder.externalsecret.targetName }}
    deletionPolicy: {{ .Values.coder.externalsecret.deletionPolicy | quote }}
  data:
    - secretKey: INT_CODER_OIDC_CLIENT_ID
      remoteRef:
        key: {{ .Values.coder.externalsecret.secretName }}
        property: INT_CODER_OIDC_CLIENT_ID
    - secretKey: INT_CODER_OIDC_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.coder.externalsecret.secretName }}
        property: INT_CODER_OIDC_CLIENT_SECRET
{{- end }}