{{- if .Values.coder.dbexternalsecret.enable }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.coder.dbexternalsecret.targetName }}
  namespace: {{ .Values.coder.namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.coder.dbexternalsecret.secretStoreRef }}
    kind: SecretStore
  refreshInterval: {{ .Values.coder.dbexternalsecret.refreshInterval }}
  target:
    name: {{ .Values.coder.dbexternalsecret.targetName }}
    deletionPolicy: {{ .Values.coder.dbexternalsecret.deletionPolicy | quote }}
  data:
    - secretKey: CODER_PG_CONNECTION_URL
      remoteRef:
        key: {{ .Values.coder.dbexternalsecret.secretName }}
        property: CODER_PG_CONNECTION_URL
        
{{- end }}