{{- if .Values.coder.serviceAccount.enable }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.coder.serviceAccount.name | quote }}
  annotations: 
    {{- toYaml .Values.coder.serviceAccount.annotations | nindent 4 }}
  labels:
    {{- include "coder.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.coder.serviceAccount.name }}-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
{{- if .Values.coder.serviceAccount.enableDeployments }}
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.coder.serviceAccount.name }}-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.coder.serviceAccount.name | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.coder.serviceAccount.name }}-role
{{- end }}