---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: cdw
  namespace: { { .Values.coder.namespace } }
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      role: arn:aws:iam::154453013990:role/eks-int-cluster-irsa-sa-irsa
