{{- if .Values.coder.service.enable }}
---
apiVersion: v1
kind: Service
metadata:
  name: coder
  namespace: {{ .Values.coder.namespace }}
  labels:
    {{- include "coder.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.coder.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.coder.service.type }}
  sessionAffinity: {{ .Values.coder.service.sessionAffinity }}
  ports:
    - name: "http"
      port: {{ .Values.coder.service.containerPort }}
      targetPort: "http"
      protocol: TCP
      nodePort: {{ .Values.coder.service.httpNodePort }}
  selector:
    {{- include "coder.selectorLabels" . | nindent 4 }}
{{- end }}
